spring.application.name=QuizApplication
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/questiondb
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA (Java Persistence API)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (good practice)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.user.name = user
spring.security.user.password= aman

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437